### ISSUE TITLE
dashingでcolcon build出来ない

### ISSUE THREAD

**Issue by liqsuq** [gbiggs/rosjp_ros2_basics#1]
ROS2に不慣れなため恐縮ですが、dashingを導入してこのプロジェクトをビルドすると下記の様な出力をして失敗しました。

CMake Error at CMakeLists.txt:34 (rclcpp_components_register_nodes):
  Unknown CMake command "rclcpp_components_register_nodes".

同様な報告は下記でもあった様です。
https://github.com/intel/ros2_object_analytics/issues/77

**Comment by gbiggs** [comment]
講習会の資料とソースはまだDashingのためにアップデートされていません。

**Comment by liqsuq** [comment]
返答ありがとうございます。

次の講習会の予定がROS Japan UGでは未定でしたので
自分の様に空いた期間に講習会を受けず、Webページの資料を試す
ユーザーのための情報として書かせていただきました。
